### ISSUE TITLE
Error 405

### ISSUE THREAD

**Issue by Prazma** [Prazma/gatemail#1]
Error 405* Occurs when sending a T-Mail.
*An un-accepted function triggers the 405 errors

**Comment by Prazma** [comment]
We are thinking about making the project offline when using GATE;MAIL.

**Comment by TomoWare** [comment]
(Hiragoon): I agree to that. The host itself is blocking it. So, I think you guys should start on creating the offline project launcher engine.

**Comment by iRoboWeb** [comment]
how about hosting a stand alone web application on a self built platform?? (if you guys are going 2 make an offline project launcher engine)

**Comment by Prazma** [comment]
We will use both methods.
Thank you.
-PT3 TM Project Lab
